// Code generated by Slice Machine. DO NOT EDIT.

import AudioList from './AudioList';
import PerformanceHistory from './PerformanceHistory';
import SongSet from './SongSet';
import Video from './Video';

export {
	AudioList,
	PerformanceHistory,
	SongSet,
	Video,
};

export const components = {
	audio_list: AudioList,
	performance_history: PerformanceHistory,
	song_set: SongSet,
	video: Video,
};
