import Head from "next/head";
import { Layout } from "@/components/layout/Layout";
import { createClient, linkResolver } from "@/prismicio";
import * as prismicH from "@prismicio/helpers";
import { FC } from "react";
import {
  HomePageDocumentData,
  ProjectDocument,
} from "@/.slicemachine/prismicio";
import ProjectCard from "@/components/project/ProjectCard";

const Home: FC<{
  pageData: HomePageDocumentData;
  projects: ProjectDocument<string>[];
}> = ({ pageData, projects }) => {
  console.log(projects);
  return (
    <>
      <Head>
        <title>{pageData.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout title={pageData.title!}>
        <main className="mt-20 mx-auto flex flex-col md:flex-row items-center md:justify-center md:content-center gap-8">
          {projects.map((project) => (
            <ProjectCard
              key={project.id}
              uid={project.uid!}
              data={project.data}
            />
          ))}
        </main>
      </Layout>
    </>
  );
};

export const getStaticProps = async ({ previewData = {} }) => {
  const client = createClient({ previewData });

  const page = await client.getSingle("home_page");

  const projects = await client.getAllByType("project");

  return {
    props: {
      pageData: page.data,
      projects,
    },
  };
};

export default Home;
